import Head from "next/head";
import c from "../styles/Home.module.scss";
import { Hexagon } from "../components/hexagon";
import useWave from "use-wave";
import Image from "next/image";
import ProfilePhoto from "../public/images/liv.png";
import { motion, Spring } from "framer-motion";
import { useState, useEffect, useRef } from "react";

const getRandomPosition = (factorX, factorY = factorX) => ({
  x: Math.random() * (factorX * 2) - factorX,
  y: Math.random() * (factorY * 2) - factorY,
});

/**
 * @type Spring
 */
const commonSpring = {
  type: "spring",
  damping: 100,
  stiffness: 50,
};

export default function Home() {
  const wave = useWave();
  const interval = useRef();
  const [tick, doTick] = useState(0);

  const baseDuration = 3;

  useEffect(() => {
    interval.current = setInterval(() => doTick(++tick), 2 * 1000);

    return () => clearInterval(interval.current);
  }, []);

  return (
    <>
      <Head>
        <title>Olivia Marolf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat&family=Rajdhani:wght@300&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={c.main}>
        <section className={c.intro}>
          <Hexagon
            initial={false}
            animate={getRandomPosition(200)}
            transition={commonSpring}
            className={c.hex1}
            color="#212328"
          />
          <Hexagon className={c.hex2} color="#212328" />
          <svg
            className={c.hexRod1}
            viewBox="0 0 841 65"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M2 36.9086L17.0001 28.3056L32 36.9086V54.0916L17.0001 62.6944L2 54.0916V36.9086Z"
              stroke="#D7D7D7"
              strokeWidth="4"
            />
            <g filter="url(#filter0_f_53_270)">
              <path
                d="M799 20.9086L814 12.3056L829 20.9086V38.0916L814 46.6944L799 38.0916V20.9086Z"
                stroke="#D7D7D7"
                strokeOpacity="0.1"
                strokeWidth="4"
              />
            </g>
            <path d="M34 45H751" stroke="#D7D7D7" strokeWidth="5" />
            <g filter="url(#filter1_f_53_270)">
              <path
                d="M80 29H797"
                stroke="#D7D7D7"
                strokeOpacity="0.1"
                strokeWidth="5"
              />
            </g>
            <defs>
              <filter
                id="filter0_f_53_270"
                x="787"
                y="0"
                width="54"
                height="59"
                filterUnits="userSpaceOnUse"
                colorInterpolationFilters="sRGB"
              >
                <feFlood floodOpacity="0" result="BackgroundImageFix" />
                <feBlend
                  mode="normal"
                  in="SourceGraphic"
                  in2="BackgroundImageFix"
                  result="shape"
                />
                <feGaussianBlur
                  stdDeviation="5"
                  result="effect1_foregroundBlur_53_270"
                />
              </filter>
              <filter
                id="filter1_f_53_270"
                x="70"
                y="16.5"
                width="737"
                height="25"
                filterUnits="userSpaceOnUse"
                colorInterpolationFilters="sRGB"
              >
                <feFlood floodOpacity="0" result="BackgroundImageFix" />
                <feBlend
                  mode="normal"
                  in="SourceGraphic"
                  in2="BackgroundImageFix"
                  result="shape"
                />
                <feGaussianBlur
                  stdDeviation="5"
                  result="effect1_foregroundBlur_53_270"
                />
              </filter>
            </defs>
          </svg>
          <header>
            <span>I AM</span>
            <h1>Olivia Marolf</h1>
            <span>▲ WEB DEVELOPER</span>
          </header>
          <svg
            className={c.hexRod2}
            viewBox="0 0 1294 62"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M34 42L1171 43" stroke="#D7D7D7" strokeWidth="5" />
            <g filter="url(#filter0_f_0_1)">
              <path
                d="M1252 20.9086L1267 12.3056L1282 20.9086V38.0916L1267 46.6944L1252 38.0916V20.9086Z"
                stroke="#D7D7D7"
                strokeOpacity="0.1"
                strokeWidth="4"
              />
            </g>
            <g filter="url(#filter1_f_0_1)">
              <path
                d="M126 28L1250 30"
                stroke="#D7D7D7"
                strokeOpacity="0.1"
                strokeWidth="5"
              />
            </g>
            <path
              d="M2 33.9086L17.0001 25.3056L32 33.9086V51.0916L17.0001 59.6944L2 51.0916V33.9086Z"
              stroke="#D7D7D7"
              strokeWidth="4"
            />
            <defs>
              <filter
                id="filter0_f_0_1"
                x="1240"
                y="0"
                width="54"
                height="59"
                filterUnits="userSpaceOnUse"
                colorInterpolationFilters="sRGB"
              >
                <feFlood floodOpacity="0" result="BackgroundImageFix" />
                <feBlend
                  mode="normal"
                  in="SourceGraphic"
                  in2="BackgroundImageFix"
                  result="shape"
                />
                <feGaussianBlur
                  stdDeviation="5"
                  result="effect1_foregroundBlur_0_1"
                />
              </filter>
              <filter
                id="filter1_f_0_1"
                x="115.996"
                y="15.5"
                width="1144.01"
                height="27"
                filterUnits="userSpaceOnUse"
                colorInterpolationFilters="sRGB"
              >
                <feFlood floodOpacity="0" result="BackgroundImageFix" />
                <feBlend
                  mode="normal"
                  in="SourceGraphic"
                  in2="BackgroundImageFix"
                  result="shape"
                />
                <feGaussianBlur
                  stdDeviation="5"
                  result="effect1_foregroundBlur_0_1"
                />
              </filter>
            </defs>
          </svg>
          <div className={c.cta}>
            <button ref={wave}>ABOUT</button>
            <button ref={wave}>CONTACT</button>
          </div>
        </section>
        <section className={c.about}>
          <h2>A BIT ABOUT ME:</h2>
          <div className={c.profile}>
            <span className={c.profileWrapper}>
              <Image
                layout="intrinsic"
                className={c.profilePhoto}
                src={ProfilePhoto}
              />
              <svg
                className={c.profileHex1}
                viewBox="0 0 147 170"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  fillRule="evenodd"
                  clipRule="evenodd"
                  d="M73.4997 170L0 127.5L0 42.4996L73.4997 0L147 42.4996L147 127.5L73.4997 170Z"
                  fill="#222328"
                />
              </svg>
              <svg
                className={c.profileHex2}
                viewBox="0 0 438 507"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  opacity="0.6"
                  fillRule="evenodd"
                  clipRule="evenodd"
                  d="M183.499 456L23 363L23 176.999L183.499 84L344 176.999L344 363L183.499 456Z"
                  fill="#222328"
                />
                <path
                  opacity="0.4"
                  d="M2 127.904L219.001 2.31082L436 127.904V379.098L219.001 504.689L2 379.098V127.904Z"
                  stroke="#222328"
                  strokeWidth="4"
                />
              </svg>
            </span>
          </div>
          <div className={c.bio}>
            <svg
              className={c.arrow1}
              viewBox="0 0 265 113"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M252.483 112.102C253.092 112.664 254.041 112.626 254.602 112.017L263.757 102.096C264.319 101.487 264.281 100.538 263.672 99.9759C263.063 99.4141 262.114 99.4523 261.552 100.061L253.415 108.88L244.596 100.743C243.987 100.181 243.038 100.219 242.476 100.828C241.914 101.437 241.952 102.386 242.561 102.948L252.483 112.102ZM0.761716 12.977C71.1375 0.50674 133.091 0.551576 177.869 15.9895C200.236 23.701 218.259 35.2325 230.937 50.9075C243.604 66.5708 251.013 86.4679 252.001 111.06L254.999 110.94C253.987 85.7821 246.39 65.2447 233.269 49.021C220.158 32.8091 201.61 21.0013 178.847 13.1533C133.363 -2.5279 70.8163 -2.48307 0.238284 10.023L0.761716 12.977Z"
                fill="#D7D7D7"
              />
            </svg>
            <p>
              As a young student, I began to take an interest in technology. I
              would spend my time teaching myself using mainly YouTube and
              documentation. After a short time, I enrolled in the Software
              Development Bootcamp at Devmountain in Lehi, UT. There I found a
              passion for web development and have continued to grow my skills
              ever since.
            </p>
            <svg
              className={c.arrow2}
              viewBox="0 0 275 234"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M1.00178 232.092C1.05283 232.919 1.7645 233.548 2.59135 233.497L16.0657 232.665C16.8926 232.614 17.5215 231.903 17.4705 231.076C17.4194 230.249 16.7078 229.62 15.8809 229.671L3.90368 230.41L3.16442 218.433C3.11338 217.606 2.40171 216.977 1.57486 217.028C0.748003 217.079 0.119087 217.791 0.170128 218.618L1.00178 232.092ZM271.091 0.752878C271.09 38.4915 260.254 64.8936 242.62 85.0085C224.939 105.177 200.327 119.14 172.548 131.791C158.663 138.115 144.042 144.088 129.125 150.351C114.222 156.609 99.0434 163.148 84.1108 170.583C54.2427 185.454 25.3009 203.933 1.37495 231.007L3.62293 232.993C27.1975 206.317 55.7674 188.046 85.4478 173.269C100.29 165.879 115.394 159.37 130.287 153.117C145.166 146.87 159.853 140.87 173.792 134.522C201.661 121.829 226.759 107.652 244.876 86.9861C263.041 66.2658 274.09 39.1378 274.091 0.752881L271.091 0.752878Z"
                fill="#D7D7D7"
              />
            </svg>
          </div>
        </section>
      </main>
    </>
  );
}
